---
title: "Auschwitz 1942-1943 Death Certificates Analysis"
author: Sima Shmuylovich
thanks: "Code and data are available at: https://github.com/sshmuylovich/holocaust.git."
date: today
date-format: long
format: pdf
number-sections: true
toc: TRUE
bibliography: references.bib
---

# Introduction {#sec-Introduction}
The Holocaust stands as one of the most harrowing and systematic genocides in human history, orchestrated by Nazi Germany under Adolf Hitler's regime during World War II. Between 1941 and 1945, six million Jews, along with millions of others deemed undesirable or enemies of the state, including Romani people, disabled individuals, Polish and Soviet prisoners, and political dissidents, were systematically murdered. The Holocaust serves as a reminder of the consequences of unchecked hate, prejudice, and the dangers of totalitarian regimes. It underscores the importance of education, remembrance, and vigilance against the forces of intolerance and discrimination to ensure such atrocities are never repeated. 

The Nazis' had a meticulous approach to record-keeping as they carried out their systematic genocidal policies. Their obsessively detailed documentation, ranging from the identification of prisoners in concentration camps to the cataloging of possessions seized from Jewish families, underscores the horrifying precision and bureaucracy with which the Holocaust was executed. The vast archives, including lists, forms, and reports, not only facilitated the industrial-scale persecution and murder of millions but also now serve as undeniable evidence of the atrocities committed. 

Auschwitz, officially known as Auschwitz-Birkenau, was the largest and most notorious of the Nazi concentration and extermination camps, located in occupied Poland. Established in 1940, it became the epicenter of the Holocaust's mass murder, where approximately 1.1 million people were killed, the majority of whom were Jews. 

The analysis of Auschwitz's 1942 - 1943 Death Certificates [@citeHolocaustData], as catalogued in the United States Holocaust Memorial Museum's Holocaust Survivors and Victims Database, is of profound importance for several reasons. First and foremost, it provides tangible documentation of the atrocities committed during one of the darkest chapters of human history, offering concrete evidence of the lives extinguished at Auschwitz Concentration Camp between 1942 and 1943, and serving not only as a historical record but also as a tool for education and remembrance. For some Holocaust victims, this may be the only proof of their existence. Analyzing these death certificates allows historians, scholars, and the public to bear witness to the scale and specificity of the genocide, helping to counteract denial and distortion of the Holocaust. Furthermore, it provides a basis for memorializing the victims, offering a semblance of dignity to those who were dehumanized and murdered, by acknowledging their individuality and the lives they led before becoming victims of Nazi persecution. 

This paper outlines the process of creating a shiny app [@citeShiny] which shows the number of people murdered by nationality, age at death, and religion and allows users to specify the groups they are interested in seeing data for. 
This paper outlines the process of creating a Shiny app, which leverages R's [@citeR] interactive web application framework [@citeShiny], designed to display the number of people murdered during the Holocaust by nationality, age at death, and religion, with customizable views for specific groups. Such an app serves several vital functions:

1. It acts as a powerful educational resource, allowing users to interact with the data to understand the scale and specifics of the Holocaust. By enabling users to select and view data according to different demographics, the app can provide personalized insights, making the historical events more relatable and impactful.

2. The app serves as a digital memorial for the victims, acknowledging their identities and the diversity of lives cut short by the Holocaust. It allows for the individual and collective remembrance of victims, not just as numbers, but as people with distinct backgrounds and stories.

3. For scholars and researchers, such an app is an invaluable tool for analyzing patterns and trends within the genocide, such as targeting specific groups, age-related vulnerabilities, and the geographical spread of Nazi crimes. This can lead to deeper understandings of the mechanisms of genocide and the societal factors involved.

4. The app provides direct access to evidence of the Holocaust, which can be an effective tool against denial and distortion. By presenting irrefutable data in an accessible and engaging manner, it helps ensure that the facts of the Holocaust remain undeniable.

5. By humanizing the statistics through the breakdown of victims' nationalities, ages, and religions, the app encourages empathy for the victims and fosters a greater appreciation for diversity and tolerance, serving as a poignant reminder of the dangers of hatred and bigotry.

# Data {#sec-Data}

The data used in this paper was gathered from the Holocaust Survivors and Victims Database hosted on the United States Holocaust Memorial Museum website [@citeHolocaustData] and analyzed using R [@citeR] with help from `dplyr` [@citeDplyr], `tidyverse` [@citeTidyverse], `shiny` [@citeShiny], `DT` [@citeDT], `ggplot2` [@citeGgplot2], `maps` [@citeMaps], `here` [@citeHere], `knitr` [@citeKnitr], and `kableExtra` [@citeKableExtra].

The dataset [@citeHolocaustData] encompassed the details of 65,280 victims as found on Death Certificates recorded at Auschwitz between July 29, 1941, and December 31, 1943. This dataset, includes the following variables:

- Last Name: The last name of the prisoners in Auschwitz concentration camp.
- First Names(s).: The first name of the prisoners in Auschwitz concentration camp.
- Date of Birth: The date of birth for prisoners in Auschwitz concentration camp, in the YYYY-MM-DD form.
- Date of Death: The date of death for prisoners in Auschwitz concentration camp, in the YYYY-MM-DD form.
- Birthplace: The birthplaces of the prisoners, recorded as a city.
- Residence: The residence of the prisoners, recorded as a city.
- Religion: The religion of the prisoners.

## Nationality
Nationality was calculated by mapping city names from the Auschwitz dataset [@citeHolocaustData] found in the Birthplace column to city names from the `world.cities` database found in the names column and accessed via R's built in maps [@citeMaps] package. The `world.cities` database comprised mainly of cities with population greater than about 40,000 but also includes all capital cities and some smaller towns [@citeMaps]. One limitation of this data matching method is that certain cities could belong to multiple countries which would result in duplicates of the same person but with different nationalities. This is limitation is evident when the mapping results in 68,188 occurrences when the original only had 65,280 [@citeHolocaustData]. Furthermore, not all cities were matched with a country. This is, however, a fairly accurate way of mapping city and country given that the original dataset provides no evidence for country of origin. 

## Age at Death
Age at death in years was calculated by subtracting date of birth from date of death for every individual. This process revealed one limitation of the original data set [@citeHolocaustData] when several calculations yielded 941 and 942. This was due to date of birth being incorrectly recorded as in the year 1000. Such inconsistencies could be explained by measurement error or data recording error. 

# Results {#section-results}
49,695 of the individuals (72.87%) were from a city that was not mapped, suggesting that the overwhelming majority of Auschwitz victims were not from large cities. Poland was the highest recorded nationality with 4,319 individuals (6.33%) which makes sense as Auschwitz is located in Poland. The four nationalities with the next highest number of individuals murdered in Auschwitz from 1942 - 1943 (in order) are France, Slovakia, Germany, and the Netherlands. The five countries with the lowest number of individuals murdered in Auschwitz from 1942 - 1943 (in order) are American Samoa, Australia, Bahamas, Bolivia, and Chile. 

2,084 of the individuals (3.06%) were not able to have their age at death calculated, suggesting missing data. Age 37
was the highest recorded age at death with 1,915 individuals (2.81%). The four ages at death with the next highest number of individuals murdered in Auschwitz from 1942 - 1943 (in order) are 38, 20, 19, 39. The five ages at death with the lowest number of individuals murdered in Auschwitz from 1942 - 1943 (in order) are 84 (tie for 1st), 89 (tie for 1st), 122 (tie for 1st), 87 (tie for 4th), 88 (tie for 4th), and 90 (tie for 4th) with 1-2 individuals each. 1.5 million children were murdered in the Holocaust. Our results show the deaths of a total of 5,782 children under 18, 407 of which had not yet reached the age of 1. 

30,648 of the individuals (44.95%) were Catholic while 30,424 of the individuals (44.62%) were Jewish. This is an extremely interesting statistic and is worth exploring further because they contradict the assumption that the majority of victims were Jewish which could be assumed from the fact that Nazi genocidal policies were targeted primarily at Jews. The four religions with the next highest number of individuals murdered in Auschwitz from 1942 - 1943 (in order) are Protestant, Greek Orthodox, and Atheist - although none make up even a tenth of Catholics or Jews. The five religions with the lowest number of individuals murdered in Auschwitz from 1942 - 1943 (in order) are Agnostic (tie for 1st), Muslim (tie for 1st), Unaffiliated (tie for 1st), Buddhist (tie for 4th), and Hussite (tie for 4th) with 1-2 individuals each.

\newpage

# References


